version: '2.0'
services:

    webapp:
        image: richarvey/nginx-php-fpm
        volumes:
            - ./web:/app
            - ./nginx/config:/etc/nginx/sites-enabled
            - ./nginx/certificates:/etc/nginx/certificates
        ports:
            - 443:443
